name: UpdateWebsite

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./.github/script/requirements.txt
    - name: build plugin pages
      run: |-
        python ./.github/script/build_plugin.py
    - name: get trade data
      run: |-
        python ./.github/script/build_trade-data.py.py
    - name: Commit and push if page changed
      run: |-
        git diff
        git config --global user.name "zmcx16-bot"
        git diff --quiet || (git add *.js && git add *.json && git commit -m "Updated plugin pages")
        git push