name: BuildPluginPage

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        architecture: x64
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install -r ./.github/script/requirements.txt
    - name: build js plugin pages
      run: |-
        python ./.github/script/build_plugin.py
    - name: install react plugin pages dependency
      run: |-
        npm --prefix ./.github/plugin-react/ install
    - name: build react plugin pages
      run: |-
        npm --prefix ./.github/plugin-react/ run build
    - name: get monitor data
      env:
        MONITOR_TOKEN_KEY: ${{ secrets.MONITOR_TOKEN_KEY }}
      run: |-
        python ./.github/script/build_monitor-data.py
    - name: Commit and push if page changed
      run: |-
        git diff
        git config --global user.name "zmcx16-bot"
        git diff --quiet || (git add *.js && git add ./plugin-react/\* && git commit -m "Updated plugin pages & monitor data")
        git push